directory: ~/audio/music
library: ~/audio/.beet.blb
import:
    move: yes
ui:
    color: yes
plugins: lyrics lastgenre mbsync fetchart scrub bpd chroma
lastgenre:
    canonical: ''
chroma:
    auto: yes
