directory: ~/library/audio/music
library: ~/library/audio/.beet.blb
import:
    move: yes
ui:
    color: yes
plugins: lyrics lastgenre mbsync fetchart scrub bpd chroma convert
lastgenre:
    canonical: ''
chroma:
    auto: yes
lyrics:
    sources: lyricwiki lyrics.com musixmatch genius
convert:
    dest: ~/zulu/com.arachnoid.sshelper/music
    format: mp3
    copy_album_art: yes
    embed: yes
